# Numpy Assingment(Saurav Kumar Rai)

# Data Types & Attributes

In [39]:
import numpy as np

In [40]:
# 1. Create a NumPy array arr of integers from 0 to 5 and print its data type.
arr1 = np.arange(6)
print("Data type of arr1:", arr1.dtype)

Data type of arr1: int64


In [41]:
# 2. Given a NumPy array arr, check if its data type is float64.
def isFloat64(arr):
    return arr.dtype == np.float64
arr2 = np.array([1.0, 2.0, 3.0])
print("Is arr2 float64?", isFloat64(arr2))

Is arr2 float64? True


In [42]:
# 3. Create a NumPy array arr with a data type of complex128 containing three complex numbers.
arr3 = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Complex128 array:", arr3)

Complex128 array: [1.+2.j 3.+4.j 5.+6.j]


In [43]:
# 4. Convert an existing NumPy array arr of integers to float32 data type.
arr4 = np.array([10, 20, 30])
arr4Float32 = arr4.astype(np.float32)
print("Converted to float32:", arr4Float32, "Type:", arr4Float32.dtype)

Converted to float32: [10. 20. 30.] Type: float32


In [44]:
# 5. Convert float64 array to float32
arr5 = np.array([1.123456789, 2.987654321], dtype=np.float64) # Generally in my jupyter notebook it is represented in float64
arr5Float32 = arr5.astype(np.float32)
print("Float64 to Float32:", arr5Float32, "Type:", arr5Float32.dtype)

Float64 to Float32: [1.1234568 2.9876542] Type: float32


In [45]:
# 6. Function to return shape, size, and data type
def arrayAttributes(arr):
    return arr.shape, arr.size, arr.dtype
print("Attributes of arr5:", arrayAttributes(arr5))

Attributes of arr5: ((2,), 2, dtype('float64'))


In [46]:
# 7. Function to return dimensionality of a NumPy array
def arrayDimension(arr):
    return arr.ndim
print("Dimensionality of arr5:", arrayDimension(arr5))

Dimensionality of arr5: 1


In [47]:
# 8. Function to return item size and total size in bytes
def itemSizeInfo(arr):
    return arr.itemsize, arr.nbytes
print("Item size and total size of arr5:", itemSizeInfo(arr5))

Item size and total size of arr5: (8, 16)


In [48]:
# 9. Function to return the strides of the given NumPy array
def arrayStrides(arr):
    return arr.strides
arr9 = np.array([[1, 2, 3], [4, 5, 6]])
print("Strides of arr9:", arrayStrides(arr9))

Strides of arr9: (24, 8)


In [49]:
# 10. Function to return both shape and strides of the given NumPy array
def shapeStrideRelationship(arr):
    return arr.shape, arr.strides
print("Shape and Strides of arr9:", shapeStrideRelationship(arr9))

Shape and Strides of arr9: ((2, 3), (24, 8))


# Array Creation

In [50]:
# 11. Create a function to return a NumPy array of zeros with n elements
def createZerosArray(n):
    return np.zeros(n)
print("Zeros array of length 5:", createZerosArray(5))

Zeros array of length 5: [0. 0. 0. 0. 0.]


In [51]:
# 12. Create a 2D array filled with ones
def createOnesMatrix(rows, cols):
    return np.ones((rows, cols))
print("Ones matrix of size 3x4:\n", createOnesMatrix(3, 4))

Ones matrix of size 3x4:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [52]:
# 13. Create a ranged NumPy array using start, stop, and step
def generateRangeArray(start, stop, step):
    return np.arange(start, stop, step)
print("Range array from 2 to 10 with step 2:", generateRangeArray(2, 10, 2))

Range array from 2 to 10 with step 2: [2 4 6 8]


In [53]:
# 14. Generate equally spaced values
def generateLinearSpace(start, stop, num):
    return np.linspace(start, stop, num)

print("Linear space:", generateLinearSpace(0, 10, 5))

Linear space: [ 0.   2.5  5.   7.5 10. ]


In [54]:
# 15. Create identity matrix
def createIdentityMatrix(n): #very easy math concept very cool to be able to code this
    return np.eye(n)

print("Identity matrix:\n", createIdentityMatrix(4))

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [55]:
# 16. Convert Python list to NumPy array
def listToNumpyArray(lst): #numpy array is much better than list of python not good for time complexity so this function can actully be useful
    return np.array(lst)

print("Converted list:", listToNumpyArray([1, 2, 3]))

Converted list: [1 2 3]


In [56]:
# 17. Create a view of a NumPy array
def createView(arr):
    return arr.view()

arr17 = np.array([10, 20, 30])
view17 = createView(arr17)
print("Original:", arr17, "| View:", view17)

Original: [10 20 30] | View: [10 20 30]


# Concatenation and Stacking

In [57]:
# 18. Concatenate two arrays along an axis
def concatenateArrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
print("Concatenated:\n", concatenateArrays(a1, a2, axis=0))

Concatenated:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [58]:
# 19. Concatenate arrays with different shapes horizontally
def horizontalConcatenateDiffShapes(a, b):
    return np.concatenate((a.reshape(-1, 1), b.reshape(-1, 1)), axis=1)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Horizontal concat diff shape:\n", horizontalConcatenateDiffShapes(a, b))

Horizontal concat diff shape:
 [[1 4]
 [2 5]
 [3 6]]


In [59]:
# 20. Vertically stack multiple arrays
def verticalStack(arr_list):
    return np.vstack(arr_list)

print("Vertically stacked:\n", verticalStack([a, b]))

Vertically stacked:
 [[1 2 3]
 [4 5 6]]


# Array Generation

In [60]:
# 21. Generate range array with step (inclusive)
def generateIntegerRange(start, stop, step):
    return np.arange(start, stop + 1, step)

print("Integer range:", generateIntegerRange(1, 10, 2))

Integer range: [1 3 5 7 9]


In [61]:
# 22. Generate 10 equally spaced values between 0 and 1
arr22 = np.linspace(0, 1, 10) # actully this function can seprate any value in equal spaces as sir taught us
print("Equally spaced [0,1]:", arr22)

Equally spaced [0,1]: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [62]:
# 23. Generate logarithmically spaced values
arr23 = np.logspace(0, 3, 5)  # from 10^0=1 to 10^3=1000 jsut saying
print("Log-spaced:", arr23)

Log-spaced: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


# I think till today questions were only about numpy and deadline of submitting Questions till panda is sunday so I only did till 23 I'll submit rest by sunday of panda